"""Compatibility facade for built-in semantic data profile contracts."""

from __future__ import annotations

from goodomics.profiles.base import PROFILE_NAMESPACE_PREFIXES
from goodomics.profiles.cbioportal import (
    CBIOPORTAL_CLINICAL_PATIENT_ATTRIBUTES,
    CBIOPORTAL_CLINICAL_SAMPLE_ATTRIBUTES,
    CBIOPORTAL_COPY_NUMBER_CONTINUOUS,
    CBIOPORTAL_COPY_NUMBER_DISCRETE_CALLS,
    CBIOPORTAL_COPY_NUMBER_LOG2,
    CBIOPORTAL_COPY_NUMBER_SEGMENTS,
    CBIOPORTAL_GENE_PANEL_MATRIX,
    CBIOPORTAL_GENERIC_ASSAY_BINARY,
    CBIOPORTAL_GENERIC_ASSAY_CATEGORICAL,
    CBIOPORTAL_GENERIC_ASSAY_LIMIT_VALUE,
    CBIOPORTAL_METHYLATION_CONTINUOUS_BETA,
    CBIOPORTAL_MRNA_EXPRESSION_CONTINUOUS,
    CBIOPORTAL_MRNA_EXPRESSION_Z_SCORE,
    CBIOPORTAL_MUTATIONS_MAF,
    CBIOPORTAL_PROTEIN_LEVEL_LOG2,
    CBIOPORTAL_PROTEIN_LEVEL_Z_SCORE,
    CBIOPORTAL_STRUCTURAL_VARIANTS,
)
from goodomics.profiles.cbioportal import (
    profile_for_meta as cbioportal_data_profile_for_meta,
)
from goodomics.profiles.multiqc import MULTIQC_METRICS, MULTIQC_PAYLOADS
from goodomics.profiles.registry import (
    all_built_in_data_profiles,
    built_in_data_profile,
    built_in_profiles,
)
from goodomics.profiles.sdk import GOODOMICS_SDK_METRICS

# Preserve the legacy module-level mapping for callers that imported it before
# source-owned profile providers existed.
BUILT_IN_DATA_PROFILES = built_in_profiles()

__all__ = [
    "BUILT_IN_DATA_PROFILES",
    "CBIOPORTAL_CLINICAL_PATIENT_ATTRIBUTES",
    "CBIOPORTAL_CLINICAL_SAMPLE_ATTRIBUTES",
    "CBIOPORTAL_COPY_NUMBER_CONTINUOUS",
    "CBIOPORTAL_COPY_NUMBER_DISCRETE_CALLS",
    "CBIOPORTAL_COPY_NUMBER_LOG2",
    "CBIOPORTAL_COPY_NUMBER_SEGMENTS",
    "CBIOPORTAL_GENERIC_ASSAY_BINARY",
    "CBIOPORTAL_GENERIC_ASSAY_CATEGORICAL",
    "CBIOPORTAL_GENERIC_ASSAY_LIMIT_VALUE",
    "CBIOPORTAL_GENE_PANEL_MATRIX",
    "CBIOPORTAL_METHYLATION_CONTINUOUS_BETA",
    "CBIOPORTAL_MRNA_EXPRESSION_CONTINUOUS",
    "CBIOPORTAL_MRNA_EXPRESSION_Z_SCORE",
    "CBIOPORTAL_MUTATIONS_MAF",
    "CBIOPORTAL_PROTEIN_LEVEL_LOG2",
    "CBIOPORTAL_PROTEIN_LEVEL_Z_SCORE",
    "CBIOPORTAL_STRUCTURAL_VARIANTS",
    "GOODOMICS_SDK_METRICS",
    "MULTIQC_METRICS",
    "MULTIQC_PAYLOADS",
    "PROFILE_NAMESPACE_PREFIXES",
    "all_built_in_data_profiles",
    "built_in_data_profile",
    "cbioportal_data_profile_for_meta",
]
