FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install uv && uv sync --all-packages --package goodomics-server

EXPOSE 8000

CMD ["uv", "run", "--package", "goodomics-server", "goodomics-server", "serve", "--host", "0.0.0.0", "--port", "8000"]
